// Usage: node scripts/content-todo.mjs  ->  writes CONTENT_TODO.md listing every TODO-CONFIRM in src/.
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const root = new URL("..", import.meta.url).pathname.replace(
  /^\/([A-Za-z]:)/,
  "$1",
);
const items = [];

const walk = (dir) => {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p);
    else if (/\.(tsx?|css)$/.test(name)) {
      readFileSync(p, "utf8")
        .split(/\r?\n/)
        .forEach((line, i) => {
          const m = line.match(/TODO-CONFIRM:?\s*(.*?)(?:\*\/\}?)?\s*$/);
          if (m)
            items.push(
              `- \`${relative(root, p).replaceAll("\\", "/")}:${i + 1}\` ${m[1].trim()}`,
            );
        });
    }
  }
};
walk(join(root, "src"));

const md = `# Content TODO

Generated by \`node scripts/content-todo.mjs\`. Each item needs client confirmation before its flag in \`src/content/flags.ts\` is switched on.

${items.join("\n")}

## Later ideas
- P1: review-request micro-app (stub route idea, not built in P0).
- Replace every placeholder image (see PLACEHOLDERS.md).
- Add exact \`geo\` coordinates to the clinic schema.
`;
writeFileSync(join(root, "CONTENT_TODO.md"), md);
console.log(`CONTENT_TODO.md written with ${items.length} items.`);
